create extension if not exists "pgcrypto";

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text default 'Daily Hisab User',
  email text,
  language text default 'bn',
  currency text default 'BDT',
  theme text default 'light',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.categories (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  created_at timestamptz default now(),
  unique (user_id, name)
);

create table if not exists public.entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  date date not null,
  category text not null,
  description text not null,
  amount numeric(12,2) not null check (amount >= 0),
  time text not null,
  method text not null check (method in ('Cash', 'bKash', 'Nagad', 'Card', 'Bank')),
  type text not null check (type in ('income', 'expense')),
  note text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.budgets (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  category text not null,
  spent numeric(12,2) default 0,
  limit_amount numeric(12,2) not null,
  color text default '#6C4CF1',
  created_at timestamptz default now(),
  unique (user_id, category)
);

create table if not exists public.recurring_expenses (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  amount numeric(12,2) not null check (amount >= 0),
  frequency text not null check (frequency in ('Daily', 'Weekly', 'Monthly')),
  next_due_date date not null,
  method text not null check (method in ('Cash', 'bKash', 'Nagad', 'Card', 'Bank')),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.reminders (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  date date not null,
  time text not null,
  completed boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.notes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  date date not null,
  tone text default 'purple',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.receipts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  entry_id bigint references public.entries(id) on delete set null,
  title text not null,
  image_url text,
  created_at timestamptz default now()
);

alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.entries enable row level security;
alter table public.budgets enable row level security;
alter table public.recurring_expenses enable row level security;
alter table public.reminders enable row level security;
alter table public.notes enable row level security;
alter table public.receipts enable row level security;

create policy "profiles own rows" on public.profiles for all using (auth.uid() = id) with check (auth.uid() = id);
create policy "categories own rows" on public.categories for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "entries own rows" on public.entries for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "budgets own rows" on public.budgets for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "recurring own rows" on public.recurring_expenses for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "reminders own rows" on public.reminders for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "notes own rows" on public.notes for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "receipts own rows" on public.receipts for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
